server:
  port: 8522
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-gs50u685c46ptsf7k.mysql.singapore.rds.aliyuncs.com:3306/yiliao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
      username: juhai
      password: zfGM0XAUHms6B5tY
  redis:
    host: r-gs5nsu05rwrseovmrm.redis.singapore.rds.aliyuncs.com
    port: 6379
    password: 30Q84d8GE4LBYzbM
#    database: 7
# 不需要登录验证的url
login:
  auth:
    urls:
      - /user/register
      - /user/login
      - /system/config
      - /project/list
      - /project/detail/*
task:
  weekreward:
    cron: 0/10 * * * * ?